[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios", "cheerio"]

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/admin"
  to = "/.netlify/functions/admin"
  status = 200

[functions."learn"]
  schedule = "0 3 * * *"